spring:
  profiles:
    active: local


  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile:
  sql:
    init:
      platform: h2